export const animationMap = {
  'clear night'                    : 'clear-night'                ,
  'cloudy'                         : 'cloudy'                     ,
  'cold'                           : 'cold'                       ,
  'dreary'                         : 'dreary'                     ,
  'flurries'                       : 'drizzle'                    ,
  'fog'                            : 'fog'                        ,
  'freezing rain'                  : 'sleet'                      ,
  'hazy moonlight night'           : 'fog-night'                  ,
  'hazy sunshine day'              : 'fog-day'                    ,
  'hot'                            : 'thermometer'                ,
  'ice'                            : 'hail'                       ,
  'intermittent clouds day'        : 'overcast'                   ,
  'intermittent clouds night'      : 'overcast'                   ,
  'mostly clear day'               : 'partly-cloudy-day'          ,
  'mostly clear night'             : 'partly-cloudy-night'        ,
  'mostly cloudy day'              : 'overcast-day'               ,
  'mostly cloudy night'            : 'overcast-night'             ,
  'mostly cloudy w/ flurries day'  : 'partly-cloudy-day-drizzle'  ,
  'mostly cloudy w/ flurries night': 'partly-cloudy-night-drizzle',
  'mostly cloudy w/ showers day'   : 'partly-cloudy-day-rain'     ,
  'mostly cloudy w/ showers night' : 'partly-cloudy-night-rain'   ,
  'mostly cloudy w/ snow day'      : 'partly-cloudy-day-snow'     ,
  'mostly cloudy w/ snow night'    : 'partly-cloudy-night-snow'   ,
  'mostly cloudy w/ t-storms day'  : 'thunderstorms-day-rain'     ,
  'mostly cloudy w/ t-storms night': 'thunderstorms-night-rain'   ,
  'mostly sunny day'               : 'clear-day'                  ,
  'partly cloudy day'              : 'partly-cloudy-day'          ,
  'partly cloudy night'            : 'partly-cloudy-night'        ,
  'partly cloudy w/ showers night' : 'partly-cloudy-night-rain'   ,
  'partly cloudy w/ t-storms night': 'thunderstorms-night-rain'   ,
  'partly sunny day'               : 'partly-cloudy-day'          ,
  'partly sunny w/ flurries day'   : 'partly-cloudy-day-drizzle'  ,
  'partly sunny w/ showers day'    : 'partly-cloudy-day-rain'     ,
  'partly sunny w/ t-storms day'   : 'thunderstorms-day-rain'     ,
  'rain and snow'                  : 'snow'                       ,
  'rain'                           : 'rain'                       ,
  'showers'                        : 'rain'                       ,
  'sleet'                          : 'sleet'                      ,
  'snow'                           : 'snow'                       ,
  'sunny'                          : 'clear-day'                  ,
  't-storms'                       : 'thunderstorms'              ,
  'windy'                          : 'wind'                       ,
}
